name: publish
on:
  push:
    branches:
      - master
    paths:
      - "*/PKGBUILD"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0
      - name: Find updated package
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail
          PKGBUILD_PATH="$(git diff --name-only HEAD HEAD~1 "*/PKGBUILD" | head -1)"
          PKGBUILD_DIR="${PKGBUILD_PATH%/*}"

          read -r PKGNAME PKGVER <<< $(awk -F' = ' '/^pkgname =/ {name=$2} /^[[:space:]]*pkgver =/ {ver=$2} END {print name, ver}' "$PKGBUILD_DIR/.SRCINFO")

          echo "PKGNAME=$PKGNAME" >> "$GITHUB_ENV"
          echo "PKGVER=$PKGVER" >> "$GITHUB_ENV"
          echo "PKGBUILD_PATH=$PKGBUILD_PATH" >> "$GITHUB_ENV"
      - name: Publish package
        uses: KSXGitHub/github-actions-deploy-aur@9dfe151cf48f26a957bbd0379c120e79cb990e13 # v2.7.2
        if: ${{ env.PKGBUILD_PATH != '' }}
        with:
          pkgname: ${{ env.PKGNAME }}
          pkgbuild: ${{ env.PKGBUILD_PATH }}
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          commit_message: ${{ env.PKGVER }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
