name: updpkgsums
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
jobs:
  updpkgsums:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Find updated package
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail
          echo "pkgbuild=$(git diff --name-only origin/main origin/${GITHUB_HEAD_REF} "*PKGBUILD" | head -1 | xargs dirname)" >> $GITHUB_ENV
      - name: Validate package
        if: ${{ env.pkgbuild != '' }}
        uses: ./.github/actions/aur
        with:
          action: "updpkgsums"
          pkgname: ${{ env.pkgbuild }}
      - name: Commit
        if: ${{ env.pkgbuild != '' }}
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
        with:
          file_pattern: "*/PKGBUILD */.SRCINFO"
