name: updpkgsums
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
    paths:
      - "*/PKGBUILD"
jobs:
  updpkgsums:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Find updated package
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail
          PKGBUILD_PATH="$(git diff --name-only origin/master origin/${GITHUB_HEAD_REF} "*/PKGBUILD" | head -1)"
          PKGBUILD_DIR="${PKGBUILD_PATH%/*}"
          echo "PKGBUILD_DIR=$PKGBUILD_DIR" >> "$GITHUB_ENV"
      - name: Validate package
        if: ${{ env.PKGBUILD_DIR != '' }}
        uses: ./.github/actions/aur
        with:
          action: "updpkgsums"
          pkgname: ${{ env.PKGBUILD_DIR }}
      - name: Commit
        if: ${{ env.PKGBUILD_DIR != '' }}
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        with:
          file_pattern: "*/PKGBUILD */.SRCINFO"
